name: simple_book_log
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  collection: ^1.15.0
  http: ^0.13.4

  device_info_plus: ^3.2.1
  flutter_bloc: ^8.0.0
  rxdart: ^0.27.3
  table_calendar: ^3.0.3
  intl: ^0.17.0
  uuid: ^3.0.5
  crypto: ^3.0.1
  tuple: ^2.0.0
  image: ^3.1.1

  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.1
  sign_in_with_apple: ^3.3.0

  flutter_signin_button: ^2.0.0
  cupertino_icons: ^1.0.2
  timelines: ^0.1.0
  charts_flutter: ^0.12.0

  url_launcher: ^6.0.18
  cached_network_image: ^3.2.0
  google_mobile_ads: ^1.0.1

  app_review: ^2.1.1+1
  flutter_email_sender: ^5.0.2

  flutter_keyboard_visibility: ^5.1.1

  in_app_purchase: ^2.0.1

  email_validator: ^2.0.1
  app_tracking_transparency: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
